### PR TITLE
fix(Lightbox): add isContained=true to close tooltip

### LINKED ISSUE #201: [Lightbox] Exit tooltip is offscreen
Exit tooltip is going off screen. It should show the Exit text

## Issue Type
Bug Report

## Component or Pattern Affected
Lightbox

## Current Behavior
Screen Shot 2019-04-29 at 2 25 00 PM

## Steps to Reproduce (for bugs)

1. 
1. 
1. 
1. 

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

### PR DESCRIPTION
**Pull request by bfbiggs**
## Related Issue

Resolves #201 

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: react/src/lib/Lightbox/index.js [hunk 1]
```diff
@@ -448,7 +448,7 @@ class Lightbox extends React.Component {
             </div>
           </div>
           <div className="md-lightbox__header-item--right">
-            <Tooltip tooltip={tooltips.exit} direction="bottom-right">
+            <Tooltip popoverProps={{ isContained: true }} tooltip={tooltips.exit} direction="bottom-right">
```
Comment (pauljeter) [inline react/src/lib/Lightbox/index.js]: With 3 props, should you put them on a new line?
