### PR TITLE
Date picker accessibility react

### LINKED ISSUE #94: Accessibility for Slider
## Issue Type
Bug Report 

## Component or Pattern Affected
Slider

## Expected Behavior
I should be able to hear what value is when I interact with the slider, similar to https://material.angular.io/components/slider/examples

## Current Behavior
Have no clue what value does the slider has

## Possible Solution
Similar to angular material slider

## Steps to Reproduce (for bugs)

1. 
1. 
1. 
1. 

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

### PR DESCRIPTION
**Pull request by jbirori**
## Description
Added aria attributes to the navigation arrows and to the individual days of the popup calendar. For the navigation arrows I labeled them with the appropriate months that they would be associated with (e.g. "next month, October"). As for the individual days, they were previously labelled with just the number that they represented and I swapped that out for a more explicit date (e.g. "Thursday, September 12th 2019"). 

## Related Issue
Resolves #94 

## Motivation and Context
The accessibility features for the current calendar date picker are not very helpful or non-existent.

## How Has This Been Tested?
I updated the jest tests, used Chrome Developer tools, and also used a screen reader to test the changes.

## Screenshots:
**Before** (If applicable):

**After**:
**Individual Day Aria Label**
Screen Shot 2019-09-12 at 3 11 27 PM

 **Previous Month Aria Label**
Screen Shot 2019-09-12 at 3 11 55 PM

Next Month Aria Label
Screen Shot 2019-09-12 at 3 12 10 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have [updated] tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: react/src/lib/DatePicker/DatePickerCalendar/index.js [hunk 1]
```diff
@@ -87,7 +87,7 @@ class DatePickerCalendar extends React.Component {
       const allPrevDaysDisabled = shouldPrevMonthDisable(date, minDate);
       return (
         <Icon
-          ariaLabel={previousArialLabel}
+          ariaLabel={`${previousArialLabel} month, ${subtractMonths(date.clone(), 1).format("MMMM")}`}
```
Comment (bfbiggs) [inline react/src/lib/DatePicker/DatePickerCalendar/index.js]: My concern here is internationalization.  If we don't give them control to replace the string completely than month will remain month always.  Perhaps we could have an internal variable that sets this value if previousAriaLabel prop isn't present?

File: react/src/lib/DatePicker/DatePickerDay/index.js [hunk 2]
```diff
@@ -45,11 +45,13 @@ class DatePickerDay extends React.Component {
           `${(isOutsideMonth && ` md-datepicker__day--outside-month`) || ''}`
         }
         onClick={this.handleClick}
-        ariaLabel={`${getDate(day)}`}
+        ariaLabel={`${day.format("dddd, MMMM Do YYYY")}`}
         aria-selected={isSelected}
         tabIndex={-1}
       >
-        {getDate(day)}
+        <div aria-label={day.format("dddd, MMMM Do YYYY")}>
```
Comment (bfbiggs) [inline react/src/lib/DatePicker/DatePickerDay/index.js]: Believe this still needs to be ariaLabel?

Comment (jbirori) [reply react/src/lib/DatePicker/DatePickerDay/index.js]: I initially thought so as well but a flag was thrown up when compiling. Found this in the [React documentation](https://reactjs.org/docs/accessibility.html):

> Note that all aria-* HTML attributes are fully supported in JSX. Whereas most DOM properties and attributes in React are camelCased, these attributes should be hyphen-cased (also known as kebab-case, lisp-case, etc) as they are in plain HTML
