### PR TITLE
fix(angular): add max-width so that tooltips wrap at some point

### LINKED ISSUE #359: [Tooltip] Angular tooltip text not wrapping
## Issue Type
 Bug Report 

## Component or Pattern Affected

Tooltip

## Expected Behavior

Tooltip should line up on item with long text

## Current Behavior

Text does not appear to wrap changing the placement of the carot
Screen Shot 2019-09-11 at 2 26 04 PM

## Steps to Reproduce (for bugs)

1. float tooltip icon right
2. long text
3. tooltip should be misaligned
4.

## Your Environment

* Library: Angular
* Version used: 8.2.6
* Browser Name and version: Chrome
* Operating System and version: Mac
* Link to your project: Control Hub

### PR DESCRIPTION
**Pull request by mathsusan**
Closes #359

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: angular/src/lib/tooltip/tooltip.component.ts [hunk 1]
```diff
@@ -16,6 +22,10 @@ export class TooltipComponent implements OnInit {
   @Input() text: string = '';
   @Input() tooltipTemplate: TemplateRef<any>;
   @Input() id: string;
+  @Input() maxWidth: number;
+
+  @HostBinding('style.max-width.px')
```
Comment (bfbiggs) [inline angular/src/lib/tooltip/tooltip.component.ts]: @daanishnasir If you have HostBinding do you need the property on the div as well?

File: angular/src/lib/tooltip/tooltip.directive.ts [hunk 2]
```diff
@@ -34,7 +40,10 @@ export class TooltipDirective implements OnInit, OnDestroy {
   @Input() tooltipTrigger: string = 'MouseEnter';
 
  /** @prop Sets the offset of the tooltip from the host */
-  @Input() offset: number = 0;
+  @Input() offset: number = 5;
+
+   /** @prop Sets the maxwidth of the tooltip */
```
Comment (bfbiggs) [inline angular/src/lib/tooltip/tooltip.directive.ts]: Missing default value in comment

File: angular/src/lib/tooltip/tooltip.directive.ts [hunk 3]
```diff
@@ -34,7 +40,10 @@ export class TooltipDirective implements OnInit, OnDestroy {
   @Input() tooltipTrigger: string = 'MouseEnter';
 
  /** @prop Sets the offset of the tooltip from the host */
-  @Input() offset: number = 0;
+  @Input() offset: number = 5;
```
Comment (bfbiggs) [inline angular/src/lib/tooltip/tooltip.directive.ts]: Is this to compensate for the arrow?
