### PR TITLE
fix(slider): Make slider accessible

### LINKED ISSUE #94: Accessibility for Slider
## Issue Type
Bug Report 

## Component or Pattern Affected
Slider

## Expected Behavior
I should be able to hear what value is when I interact with the slider, similar to https://material.angular.io/components/slider/examples

## Current Behavior
Have no clue what value does the slider has

## Possible Solution
Similar to angular material slider

## Steps to Reproduce (for bugs)

1. 
1. 
1. 
1. 

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

### PR DESCRIPTION
**Pull request by jbirori**
## Description
Included aria attributes to the div wrapping the slider to make it more accessible. If the slider has one pointer then it uses the `aria-valuenow` attribute to share the current value. If the slider has two pointers it uses the `aria-valuetext` attribute to share the value of both pointers in the following format:
 `"Low is Math.min(sliderLow, sliderHigh), high is Math.max(sliderLow, sliderHigh)"`
The min/max operations handle the case where the two pointers can cross each other.

**Alternate Solution**: In testing with a screen reader, I found that it actually makes more sense to add the aria attributes directly to the pointers so that the user can be updated on movements of the pointers. However, this would require adding in one or more props to the SliderPointer component to make it aware of its current value. Any thoughts on which approach should be prioritized?

## Related Issue
Resolves #94 (for React)

## Motivation and Context
The slider currently has no accessibility features.

## How Has This Been Tested?
I updated the jest tests, used Chrome Developer tools, and also used a screen reader to test the changes.

## Screenshots:
**Before** (If applicable):
There were no aria attributes

**After**:
`aria-valuenow` for one slider pointer:
Screen Shot 2019-09-10 at 3 42 38 PM

`aria-valuetext` for two slider pointers:
Screen Shot 2019-09-10 at 3 41 29 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have [updated] tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: react/src/lib/Slider/index.js [hunk 1]
```diff
@@ -155,10 +155,24 @@ class Slider extends React.Component {
     };
 
     return (
-      <div className={
-        `md-slider ${className}` +
-        `${(disabled && ` md-slider--disabled`) || ''}` +
-        `${(className && ` ${className}`) || ''}`
```
Comment (jbirori) [inline react/src/lib/Slider/index.js]: Also this is a bit redundant because className is already added 2 lines up. I suggest we remove that and stay with this conditional line.

File: react/src/lib/Slider/index.js [hunk 2]
```diff
@@ -155,10 +155,24 @@ class Slider extends React.Component {
...
+      <div 
+        className={
+          `md-slider ${className}` +
```
Comment (bfbiggs) [inline react/src/lib/Slider/index.js]: Agree with removing class name here as well because it also adds unnecessary spaces.
